# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "The L Show"

author:
  name:             Lawrence Choi
  github:           github.com/l2choi
  linkedin:         ttps://www.linkedin.com/in/choilawrence
  email:            l2choi@uwaterloo.ca

# Google-analytics (not used)
google-analytics:
  id:               ""

# Disqus (not used)
disqus:
  id:               ""

# URL
url:                "https://l2choi.github.io"
#url:               "localhost:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Canada/Eastern
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/l2choi"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
